version: "3.9"
services:
  node1:
    build:
      context: ./nodes/
      dockerfile: Dockerfile
    networks:
      - paxos_backend
    environment: 
      - SERVER_ID=node1

  node2:
    build:
      context: ./nodes/
      dockerfile: Dockerfile
    networks:
      - paxos_backend
    environment: 
      - SERVER_ID=node2

  node3:
    build:
      context: ./nodes/
      dockerfile: Dockerfile
    networks:
      - paxos_backend
    environment: 
      - SERVER_ID=node3

  # Only loadbalancer is visible to outside of the network
  loadbalancer:
    build:
      context: ./rproxy/
      dockerfile: Dockerfile
    networks:
      - paxos_backend
    ports:
      - 8081:8081

networks:
  paxos_backend:
