version: "3.9"
services:
  node1:
    build:
      context: ./nodes/
      dockerfile: Dockerfile
    networks:
      - paxos_backend

  node2:
    build:
      context: ./nodes/
      dockerfile: Dockerfile
    networks:
      - paxos_backend

  node3:
    build:
      context: ./nodes/
      dockerfile: Dockerfile
    networks:
      - paxos_backend

  loadbalancer:
    build:
      context: ./rproxy/
      dockerfile: Dockerfile
    networks:
      - paxos_backend
    ports:
      - 8081:8081

networks:
  paxos_backend:
