version: "3.9"
services:
  node1:
    build:
      context: ./nodes/
      dockerfile: Dockerfile
    networks:
      - paxos_backend
    ports:
      - 8001:80

  node2:
    build:
      context: ./nodes/
      dockerfile: Dockerfile
    networks:
      - paxos_backend
    ports:
      - 8002:80

  node3:
    build:
      context: ./nodes/
      dockerfile: Dockerfile
    networks:
      - paxos_backend
    ports:
      - 8003:80

networks:
  paxos_backend:
